import re
import os
from urllib.parse import quote_plus


class ContentSanitizer:
    """Post-processing sanitizer for LLM-generated article content.
    
    Fixes common formatting issues (em dashes, bold-as-heading, heading spacing)
    and enforces Amazon product links with optional affiliate tagging.
    """

    def __init__(self):
        self.affiliate_tag = os.getenv("AMAZON_AFFILIATE_TAG", "")

    def sanitize_plain_text(self, text: str) -> str:
        """Strip all Markdown bold and italic markers from plain text fields."""
        if not text:
            return text
        # Strip bold/italic wrappers
        text = re.sub(r'[\*_]{1,2}([^*_]+)[\*_]{1,2}', r'\1', text)
        # Strip any leftover stray markers
        for marker in ["**", "__", "*", "_"]:
            text = text.replace(marker, "")
        return text.strip()

    def sanitize(self, content: str, article_type: str | None = None) -> str:
        """Run all formatting sanitization steps on article Markdown content.
        
        Args:
            content: The article Markdown content.
            article_type: The format type of the article (e.g. tutorial).
        """
        content = self._remove_dashes(content)
        
        # Skip unwrapping code blocks for tutorial articles to preserve code blocks and syntax highlighting
        is_tutorial = False
        if article_type is not None:
            if hasattr(article_type, "value"):
                is_tutorial = article_type.value == "tutorial"
            else:
                is_tutorial = str(article_type).lower().strip() == "tutorial"

        if not is_tutorial:
            content = self._unwrap_code_blocks(content)
            
        content = self._strip_markdown_markers_from_headings(content)
        content = self._fix_bold_headings(content)
        content = self._split_inlined_lists(content)
        content = self._fix_heading_spacing(content)
        return content



    def enforce_amazon_links(self, content: str, entities: list) -> str:
        """Ensure every product entity has an Amazon search link by wrapping the name.
        
        Args:
            content: The article Markdown content.
            entities: List of entity dicts from EntityExtractor,
                      each with "name" and "type" keys.
        
        Returns:
            Modified content with Amazon links wrapped around product names.
        """
        # Step 1: Strip any explicit "Check Price on Amazon" style links (and formatting)
        # generated by the LLM, so they can be replaced by clean inline entity links.
        content = re.sub(
            r'\s*[\*\_]*\s*\[(?:Check Price on Amazon|Buy on Amazon|Check on Amazon|Amazon|Check Price)\]\(https?://[^)\s]+\)\s*[\*\_]*',
            '',
            content,
            flags=re.IGNORECASE
        )

        # Filter to only product-type entities
        product_entities = [
            e for e in entities
            if isinstance(e, dict) and e.get("type", "").lower() == "product"
        ]

        for entity in product_entities:
            entity_name = entity.get("name", "").strip()
            if not entity_name or len(entity_name) < 3:
                continue

            # Skip if this product already has an Amazon link nearby
            if self._has_amazon_link_nearby(content, entity_name):
                continue

            # Build the Amazon search URL
            encoded_name = quote_plus(entity_name)
            amazon_url = f"https://www.amazon.com/s?k={encoded_name}"
            if self.affiliate_tag:
                amazon_url += f"&tag={self.affiliate_tag}"

            # Wrap the entity name itself in the link
            content = self._wrap_entity_in_link(content, entity_name, amazon_url)

        # Append affiliate tag to any existing Amazon links that are missing it
        if self.affiliate_tag:
            content = self._append_affiliate_tag(content)

        return content

    # ── Private helpers ─────────────────────────────────────────────

    @staticmethod
    def _remove_dashes(content: str) -> str:
        """Replace em dashes and en dashes with commas."""
        content = content.replace("\u2014", ",")   # em dash —
        content = content.replace("\u2013", ",")   # en dash –
        return content

    @staticmethod
    def _fix_bold_headings(content: str) -> str:
        """Convert standalone bold-only lines into ## headings and strip bold markers from existing headings of any level."""
        # 1. Strip bold/italic wrappers from existing headings of any level (e.g. '## **Heading**' -> '## Heading')
        content = re.sub(r'^(\s*#+)\s*[\*_]{1,2}([^*_]+)[\*_]{1,2}\s*$', r'\1 \2', content, flags=re.MULTILINE)
        
        # 2. Convert standalone bold-only lines into ## headings
        pattern = re.compile(r'^(\s*)\*\*([^*]+)\*\*\s*$', re.MULTILINE)
        return pattern.sub(r'## \2', content)

    @staticmethod
    def _strip_markdown_markers_from_headings(content: str) -> str:
        """Strip bold and italic markers from any Markdown heading line.
        
        Handles all edge cases: ## **Heading**, ## __Heading__, ## *Heading*,
        ## _Heading_, ## ***Heading***, and mixed cases like ## **Bold *and italic***.
        """
        lines = content.split('\n')
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith('#'):
                # Separate the heading prefix (e.g. '##') from the text
                match = re.match(r'^(\s*#+)\s*(.*)', line)
                if match:
                    prefix = match.group(1)
                    text = match.group(2)
                    # Iteratively strip bold/italic wrappers until stable
                    prev = None
                    while text != prev:
                        prev = text
                        # Strip wrapping bold/italic markers
                        text = re.sub(r'^[\*_]{1,3}(.+?)[\*_]{1,3}$', r'\1', text.strip())
                    # Strip any remaining stray markers
                    text = text.replace('**', '').replace('__', '')
                    text = text.replace('*', '').replace('_', '')
                    lines[i] = f"{prefix} {text.strip()}"
        return '\n'.join(lines)

    @staticmethod
    def _split_inlined_lists(content: str) -> str:
        """Split inline checklists (e.g. '✅ Item 1 ✅ Item 2') into bullet lists."""
        lines = content.split('\n')
        result = []
        in_code_block = False
        for line in lines:
            stripped = line.strip()
            
            # Toggle code block state
            if stripped.startswith('```'):
                in_code_block = not in_code_block
                result.append(line)
                continue

            if in_code_block or stripped.startswith('#') or '|' in stripped:
                result.append(line)
                continue

            if '✅' in stripped or '❌' in stripped:
                # Find indices of both emojis
                indices = [stripped.find('✅'), stripped.find('❌')]
                valid_indices = [idx for idx in indices if idx != -1]
                if not valid_indices:
                    result.append(line)
                    continue
                first_idx = min(valid_indices)
                
                prefix = stripped[:first_idx].strip()
                emoji_part = stripped[first_idx:]
                
                parts = re.findall(r'([✅❌])\s*([^✅❌]+)', emoji_part)
                if len(parts) > 1:
                    bullet_lines = []
                    # Keep prefix if present (e.g., "Pros:")
                    if prefix and prefix not in ["-", "*"]:
                        bullet_lines.append(prefix)
                    for emoji, text in parts:
                        bullet_lines.append(f"- {emoji} {text.strip()}")
                    result.append('\n'.join(bullet_lines))
                    continue
            result.append(line)
        return '\n'.join(result)




    @staticmethod
    def _unwrap_code_blocks(content: str) -> str:
        """Convert fenced code blocks into blockquotes.
        
        The LLM wraps specifications and summaries in triple-backtick code
        blocks, which render as ugly monospaced text on the blog frontend.
        This converts them into blockquotes for cleaner display.
        """
        lines = content.split('\n')
        result: list[str] = []
        in_code_block = False

        for line in lines:
            stripped = line.strip()
            # Detect code fence (``` or ```markdown, ```text, etc.)
            if stripped.startswith('```'):
                if not in_code_block:
                    # Opening fence — skip this line
                    in_code_block = True
                    continue
                else:
                    # Closing fence — skip this line
                    in_code_block = False
                    continue

            if in_code_block:
                # Convert code block content to blockquote
                if stripped:
                    result.append(f"> {stripped}")
                else:
                    result.append(">")
            else:
                result.append(line)

        return '\n'.join(result)

    @staticmethod
    def _fix_heading_spacing(content: str) -> str:
        """Ensure a blank line exists before and after every heading."""
        lines = content.split('\n')
        result: list[str] = []

        for i, line in enumerate(lines):
            stripped = line.strip()
            is_heading = stripped.startswith('#')

            if is_heading:
                # Blank line before heading (unless it's the first line or already blank)
                if result and result[-1].strip() != '':
                    result.append('')
                result.append(line)
            else:
                # Blank line after heading
                if result and result[-1].strip().startswith('#') and stripped != '':
                    result.append('')
                result.append(line)

        return '\n'.join(result)

    @staticmethod
    def _has_amazon_link_nearby(content: str, entity_name: str) -> bool:
        """Check whether the entity already has an Amazon link within 300 chars."""
        lower_content = content.lower()
        lower_entity = entity_name.lower()
        pos = lower_content.find(lower_entity)
        if pos == -1:
            return True  # Entity not found in text at all; nothing to inject

        window = lower_content[pos:pos + len(entity_name) + 300]
        return "amazon.com" in window

    @staticmethod
    def _wrap_entity_in_link(content: str, entity_name: str, amazon_url: str) -> str:
        """Wrap the first body-text mention of *entity_name* in a Markdown link to *amazon_url*."""
        lines = content.split('\n')
        replaced = False
        result: list[str] = []
        in_code_block = False

        for line in lines:
            stripped = line.strip()

            # Toggle code block state
            if stripped.startswith('```'):
                in_code_block = not in_code_block
                result.append(line)
                continue

            if replaced or in_code_block:
                result.append(line)
                continue

            # Skip headings, empty lines, and lines that already have amazon links
            if stripped.startswith('#') or not stripped or 'amazon.com' in line.lower():
                result.append(line)
                continue

            # Case-insensitive search for entity in line with word boundaries
            pattern = re.compile(rf'\b({re.escape(entity_name)})\b', re.IGNORECASE)
            match = pattern.search(line)
            if not match:
                result.append(line)
                continue

            idx = match.start(1)
            end_idx = match.end(1)

            # Don't wrap if inside an existing Markdown link
            before = line[:idx]
            if '[' in before:
                bracket_pos = before.rfind('[')
                between = before[bracket_pos:]
                if '](' not in between:
                    result.append(line)
                    continue

            # Grab the actual casing of the entity as written in the text
            actual_name_in_text = match.group(1)
            link_md = f"[{actual_name_in_text}]({amazon_url})"

            line = line[:idx] + link_md + line[end_idx:]
            replaced = True
            result.append(line)

        return '\n'.join(result)

    def _append_affiliate_tag(self, content: str) -> str:
        """Append the affiliate tag to existing Amazon links that lack one."""
        tag = self.affiliate_tag

        def _add_tag(match: re.Match) -> str:
            url = match.group(1)
            if f"tag={tag}" in url:
                return url
            if "tag=" in url:
                return url  # Different tag already present; don't overwrite
            return f"{url}&tag={tag}"

        return re.sub(
            r'(https://www\.amazon\.com/s\?k=[^)\s]+)',
            _add_tag,
            content,
        )
