import re
import os
from urllib.parse import quote_plus
from typing import List, Dict, Any


class ContentSanitizer:
    """Post-processing sanitizer for LLM-generated article content.
    
    Fixes formatting issues (dashes, bold-as-heading, heading spacing),
    enforces smart entity linking (Amazon for physical goods, homepage/clean links for software),
    and generates visual product callout cards.
    """

    NON_PHYSICAL_CATEGORIES = {
        "web services",
        "digital security",
        "creative software",
        "productivity software",
        "ai tools",
        "personal finance",
        "saving money",
        "remote work",
        "career & productivity",
        "education & learning",
        "solo & group travel",
    }

    def __init__(self):
        self.affiliate_tag = os.getenv("AMAZON_AFFILIATE_TAG", "")

    def sanitize_plain_text(self, text: str) -> str:
        """Strip all Markdown bold and italic markers from plain text fields."""
        if not text:
            return text
        text = re.sub(r'[\*_]{1,2}([^*_]+)[\*_]{1,2}', r'\1', text)
        for marker in ["**", "__", "*", "_"]:
            text = text.replace(marker, "")
        return text.strip()

    def sanitize(self, content: str, article_type: str | None = None) -> str:
        """Run all formatting sanitization steps on article Markdown content."""
        content = self._remove_dashes(content)
        
        is_tutorial = False
        if article_type is not None:
            if hasattr(article_type, "value"):
                is_tutorial = article_type.value == "tutorial"
            else:
                is_tutorial = str(article_type).lower().strip() == "tutorial"

        if not is_tutorial:
            content = self._unwrap_code_blocks(content)
            
        content = self._strip_markdown_markers_from_headings(content)
        content = self._fix_bold_headings(content)
        content = self._split_inlined_lists(content)
        content = self._fix_heading_spacing(content)
        return content

    def enforce_amazon_links(self, content: str, entities: list, category: str = "") -> str:
        """Smart entity link injection:
        - Wraps physical product entities in Amazon search links (with affiliate tag).
        - Avoids forcing software, SaaS, or non-physical items into Amazon search URLs.
        """
        # Step 1: Strip any explicit "Check Price on Amazon" style links generated by the LLM
        content = re.sub(
            r'\s*[\*\_]*\s*\[(?:Check Price on Amazon|Buy on Amazon|Check on Amazon|Amazon|Check Price)\]\(https?://[^)\s]+\)\s*[\*\_]*',
            '',
            content,
            flags=re.IGNORECASE
        )

        category_lower = category.lower().strip()
        is_non_physical = category_lower in self.NON_PHYSICAL_CATEGORIES

        # Filter to only physical product entities (skip software/companies in digital categories)
        product_entities = [
            e for e in entities
            if isinstance(e, dict)
            and e.get("type", "").lower() == "product"
            and not (is_non_physical and e.get("type", "").lower() in {"software", "company"})
        ]

        for entity in product_entities:
            entity_name = entity.get("name", "").strip()
            if not entity_name or len(entity_name) < 3:
                continue

            # Skip if this is a software product in a software/service category
            if is_non_physical:
                continue

            # Build the Amazon search URL
            encoded_name = quote_plus(entity_name)
            amazon_url = f"https://www.amazon.com/s?k={encoded_name}"
            if self.affiliate_tag:
                amazon_url += f"&tag={self.affiliate_tag}"

            content = self._wrap_entity_in_link(content, entity_name, amazon_url)

        # Append affiliate tag to any existing Amazon links that lack one
        if self.affiliate_tag:
            content = self._append_affiliate_tag(content)

        return content

    def inject_product_cards(self, content: str, entities: list, product_images: dict = None) -> str:
        """Inject styled visual product highlight cards under top product H3 sections."""
        if not entities:
            return content

        product_images = product_images or {}
        product_entities = [
            e for e in entities
            if isinstance(e, dict) and e.get("type", "").lower() == "product" and len(e.get("name", "").strip()) > 3
        ]

        if not product_entities:
            return content

        # Create cards for up to the top 2 recommended products (Top Pick and Runner-Up/Budget)
        badges = ["Top Pick", "Best Value", "Alternative Pick"]
        lines = content.split('\n')
        new_lines = []
        card_count = 0

        for line in lines:
            new_lines.append(line)
            stripped = line.strip()

            # Detect H3 product headings like "### JBL Endurance Peak 3: Best Overall" or "### 1. Dell XPS 13"
            if stripped.startswith('###') and card_count < min(2, len(product_entities)):
                # Check if this heading matches a product entity
                matched_product = None
                for pe in product_entities:
                    pname = pe["name"]
                    if pname.lower() in stripped.lower():
                        matched_product = pname
                        break

                if matched_product:
                    badge = badges[card_count]
                    card_html = self._render_product_card(
                        product_name=matched_product,
                        badge=badge,
                        image_url=product_images.get(matched_product, ""),
                        affiliate_tag=self.affiliate_tag
                    )
                    new_lines.append("")
                    new_lines.append(card_html)
                    new_lines.append("")
                    card_count += 1

        return '\n'.join(new_lines)

    def _render_product_card(self, product_name: str, badge: str, image_url: str = "", affiliate_tag: str = "") -> str:
        """Generate a self-contained, responsive HTML product showcase card."""
        encoded = quote_plus(product_name)
        amazon_url = f"https://www.amazon.com/s?k={encoded}"
        if affiliate_tag:
            amazon_url += f"&tag={affiliate_tag}"

        image_html = ""
        if image_url:
            image_html = f'''
  <div style="flex: 0 0 140px; max-width: 160px; margin: 0 auto; text-align: center;">
    <img src="{image_url}" alt="{product_name}" loading="lazy" style="max-width: 100%; max-height: 140px; object-fit: contain; border-radius: 8px;" />
  </div>'''

        badge_bg = "#eff6ff" if badge == "Top Pick" else "#f0fdf4"
        badge_color = "#1d4ed8" if badge == "Top Pick" else "#15803d"

        card = f'''<div class="product-highlight-card" style="border: 1px solid #e2e8f0; border-radius: 16px; padding: 20px; margin: 24px 0; background-color: #ffffff; box-shadow: 0 4px 12px rgba(0,0,0,0.03); display: flex; flex-direction: row; flex-wrap: wrap; gap: 20px; align-items: center;">{image_html}
  <div style="flex: 1; min-width: 240px;">
    <div style="display: flex; gap: 8px; align-items: center; margin-bottom: 6px;">
      <span style="background-color: {badge_bg}; color: {badge_color}; font-size: 0.75rem; font-weight: 700; padding: 3px 10px; border-radius: 9999px; text-transform: uppercase; letter-spacing: 0.05em;">{badge}</span>
      <span style="color: #f59e0b; font-weight: bold; font-size: 0.875rem;">⭐ Editor's Choice</span>
    </div>
    <h4 style="margin: 0 0 8px 0; font-size: 1.25rem; color: #0f172a; font-family: inherit;">{product_name}</h4>
    <div style="margin-top: 12px;">
      <a href="{amazon_url}" target="_blank" rel="nofollow sponsored noopener" style="display: inline-block; background-color: #2563eb; color: #ffffff; font-weight: 600; padding: 9px 18px; border-radius: 8px; text-decoration: none; font-size: 0.875rem; transition: background-color 0.2s;">Check Price on Amazon &rarr;</a>
    </div>
  </div>
</div>'''
        return card

    # ── Private helpers ─────────────────────────────────────────────

    @staticmethod
    def _remove_dashes(content: str) -> str:
        """Replace em dashes (—) and en dashes (–) with clean colons or spaced hyphens."""
        # Replace dash following bold markers or list prefixes with colon (e.g., "**Feature** — description" -> "**Feature**: description")
        content = re.sub(r'(\*\*[^*]+\*\*)\s*[\u2014\u2013]\s*', r'\1: ', content)
        # Replace standalone em/en dashes inside sentences with spaced hyphens
        content = content.replace("\u2014", " - ")
        content = content.replace("\u2013", " - ")
        # Clean up any accidental double spaces or comma-space artifacts
        content = re.sub(r'\s{2,}', ' ', content)
        return content

    @staticmethod
    def _fix_bold_headings(content: str) -> str:
        """Convert standalone bold-only lines into ## headings and strip bold markers from existing headings of any level."""
        content = re.sub(r'^(\s*#+)\s*[\*_]{1,2}([^*_]+)[\*_]{1,2}\s*$', r'\1 \2', content, flags=re.MULTILINE)
        pattern = re.compile(r'^(\s*)\*\*([^*]+)\*\*\s*$', re.MULTILINE)
        return pattern.sub(r'## \2', content)

    @staticmethod
    def _strip_markdown_markers_from_headings(content: str) -> str:
        """Strip bold and italic markers from any Markdown heading line."""
        lines = content.split('\n')
        for i, line in enumerate(lines):
            stripped = line.strip()
            if stripped.startswith('#'):
                match = re.match(r'^(\s*#+)\s*(.*)', line)
                if match:
                    prefix = match.group(1)
                    text = match.group(2)
                    prev = None
                    while text != prev:
                        prev = text
                        text = re.sub(r'^[\*_]{1,3}(.+?)[\*_]{1,3}$', r'\1', text.strip())
                    text = text.replace('**', '').replace('__', '')
                    text = text.replace('*', '').replace('_', '')
                    lines[i] = f"{prefix} {text.strip()}"
        return '\n'.join(lines)

    @staticmethod
    def _split_inlined_lists(content: str) -> str:
        """Split inline checklists into formatted bullet lists."""
        lines = content.split('\n')
        result = []
        in_code_block = False
        for line in lines:
            stripped = line.strip()
            if stripped.startswith('```'):
                in_code_block = not in_code_block
                result.append(line)
                continue

            if in_code_block or stripped.startswith('#') or '|' in stripped:
                result.append(line)
                continue

            if '✅' in stripped or '❌' in stripped:
                indices = [stripped.find('✅'), stripped.find('❌')]
                valid_indices = [idx for idx in indices if idx != -1]
                if not valid_indices:
                    result.append(line)
                    continue
                first_idx = min(valid_indices)
                prefix = stripped[:first_idx].strip()
                emoji_part = stripped[first_idx:]
                parts = re.findall(r'([✅❌])\s*([^✅❌]+)', emoji_part)
                if len(parts) > 1:
                    bullet_lines = []
                    if prefix and prefix not in ["-", "*"]:
                        bullet_lines.append(prefix)
                    for emoji, text in parts:
                        bullet_lines.append(f"- {emoji} {text.strip()}")
                    result.append('\n'.join(bullet_lines))
                    continue
            result.append(line)
        return '\n'.join(result)

    @staticmethod
    def _unwrap_code_blocks(content: str) -> str:
        """Convert fenced code blocks into blockquotes for non-tutorial articles."""
        lines = content.split('\n')
        result: list[str] = []
        in_code_block = False

        for line in lines:
            stripped = line.strip()
            if stripped.startswith('```'):
                in_code_block = not in_code_block
                continue

            if in_code_block:
                if stripped:
                    result.append(f"> {stripped}")
                else:
                    result.append(">")
            else:
                result.append(line)

        return '\n'.join(result)

    @staticmethod
    def _fix_heading_spacing(content: str) -> str:
        """Ensure a blank line exists before and after every heading."""
        lines = content.split('\n')
        result: list[str] = []

        for i, line in enumerate(lines):
            stripped = line.strip()
            is_heading = stripped.startswith('#')

            if is_heading:
                if result and result[-1].strip() != '':
                    result.append('')
                result.append(line)
            else:
                if result and result[-1].strip().startswith('#') and stripped != '':
                    result.append('')
                result.append(line)

        return '\n'.join(result)

    @staticmethod
    def _wrap_entity_in_link(content: str, entity_name: str, amazon_url: str) -> str:
        """Wrap the first valid body-text mention of entity_name in a Markdown link."""
        lines = content.split('\n')
        replaced = False
        result: list[str] = []
        in_code_block = False

        for line in lines:
            stripped = line.strip()

            if stripped.startswith('```'):
                in_code_block = not in_code_block
                result.append(line)
                continue

            if replaced or in_code_block:
                result.append(line)
                continue

            # Skip headings, empty lines, and lines that already have amazon links
            if stripped.startswith('#') or not stripped or 'amazon.com' in line.lower():
                result.append(line)
                continue

            pattern = re.compile(rf'\b({re.escape(entity_name)})\b', re.IGNORECASE)
            match = pattern.search(line)
            if not match:
                result.append(line)
                continue

            idx = match.start(1)
            end_idx = match.end(1)

            # Don't wrap if already inside an existing Markdown link
            before = line[:idx]
            if '[' in before:
                bracket_pos = before.rfind('[')
                between = before[bracket_pos:]
                if '](' not in between and ')' not in between:
                    result.append(line)
                    continue

            actual_name_in_text = match.group(1)
            link_md = f"[{actual_name_in_text}]({amazon_url})"

            line = line[:idx] + link_md + line[end_idx:]
            replaced = True
            result.append(line)

        return '\n'.join(result)

    def _append_affiliate_tag(self, content: str) -> str:
        """Append the affiliate tag to existing Amazon links that lack one."""
        tag = self.affiliate_tag

        def _add_tag(match: re.Match) -> str:
            url = match.group(1)
            if f"tag={tag}" in url:
                return url
            if "tag=" in url:
                return url
            return f"{url}&tag={tag}"

        return re.sub(
            r'(https://www\.amazon\.com/s\?k=[^)\s]+)',
            _add_tag,
            content,
        )
